services:
  mariadb:
    image: mariadb:11
    container_name: coupon-mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root1234
      MARIADB_DATABASE: coupon_db
      MARIADB_USER: coupon_user
      MARIADB_PASSWORD: coupon_pass
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: coupon-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mariadb_data: